version: 2.1

jobs:
  build:
      docker:
        - image: circleci/node:13.8.0
      steps:
        - checkout
        - run: npm i
        - save_cache:
              paths:
                - /src/node_modules
              key: "npm-packages"
        - run: npm run lint
           

  test:
      docker:
        - image: circleci/node:13.8.0
      steps:
        - checkout
        - restore_cache:
            keys:
              - "npm-packages"
        - run: npm i
        - run: npm run test
       
              
  analyze:
      docker:
        - image: circleci/node:13.8.0
      steps:
        - checkout
        - run: npm i
        - run: npm audit

          
workflows:
  pipe_line_workflows:
    jobs:
      - build
      - test:
          requires:
            - build
      - analyze
          requires:
            - test
